### ISSUE TITLE
NullPointerException at isCactusFlower(BetterWorld.java:383)

### ISSUE THREAD

**Issue by SkurczMuzgu** [Pronink/vegansWay#1]
Hi Pronink,
Thank you for a fantastic plugin. my family loves it. 
I recently looked into the server logs and is seems that VegansWay throws NPE every 4-5 seconds. Here's the relevant excerpt from the log file. I use default config file. 

```
[04:08:17] [Server thread/INFO]: Starting minecraft server version 1.12.2
[04:08:17] [Server thread/WARN]: To start the server with more ram, launch it as "java -Xmx1024M -Xms1024M -jar minecraft_server.jar"
[04:08:17] [Server thread/INFO]: Loading properties
[04:08:17] [Server thread/INFO]: Default game type: SURVIVAL
[04:08:17] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-4bd94dc-bacaf92 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
...
You use the latest version of VegansWay: v1.1

[04:08:26] [Server thread/WARN]: [VegansWay] Task #2 for VegansWay v1.1 generated an exception
java.lang.NullPointerException: null
	at VegansWay.BetterWorld.isCactusFlower(BetterWorld.java:383) ~[?:?]
	at VegansWay.BetterWorld.findFloatingFlowers(BetterWorld.java:151) ~[?:?]
	at VegansWay.Main$1.run(Main.java:130) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[04:08:31] [Server thread/WARN]: [VegansWay] Task #2 for VegansWay v1.1 generated an exception
java.lang.NullPointerException: null
	at VegansWay.BetterWorld.isCactusFlower(BetterWorld.java:383) ~[?:?]
	at VegansWay.BetterWorld.findFloatingFlowers(BetterWorld.java:151) ~[?:?]
	at VegansWay.Main$1.run(Main.java:130) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[04:08:36] [Server thread/WARN]: [VegansWay] Task #2 for VegansWay v1.1 generated an exception
java.lang.NullPointerException: null
	at VegansWay.BetterWorld.isCactusFlower(BetterWorld.java:383) ~[?:?]
	at VegansWay.BetterWorld.findFloatingFlowers(BetterWorld.java:151) ~[?:?]
	at VegansWay.Main$1.run(Main.java:130) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]

**Comment by Pronink** [comment]
Hi @SkurczMuzgu !
Thanks for your feedback :-)
I'm going to investigate why this is happening. You will have news tomorrow.
Greetings and I'm glad you like the plugin <3

**Comment by Pronink** [comment]
Hi again @SkurczMuzgu 
I'm sorry but I can not reproduce your error on my server. Could you give me more details about your server (plugins used, java version ...)?
Regards !! :-)
